$schema: "http://json-schema.org/draft-07/schema#"

have_fun: true
code_review:
  disable: true
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: true
    summary: true
    code_review: true
    include_drafts: true
ignore_patterns: []
